name-template: 'Release v$NEXT_PATCH_VERSION 🌈'
tag-template: '$NEXT_PATCH_VERSION'
branches: 'master'
categories:
  - title: '🚀 Features'
    labels:
      - 'actions: new feature'
      - 'actions: enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'actions: bug'
      - 'actions: bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore: documentation'
      - 'chore: dependencies'
exclude-labels:
  - 'skip-changelog'
  - 'actions: release'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
